name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10-dev'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up target Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Pick environment to run
        run: |
          import platform; import os; import sys; import codecs
          base = '.'.join(map(str, sys.version_info[:2]))
          env = 'BASE={}\n'.format(base)
          print('Picked:\n{}for{}'.format(env, sys.version))
          with codecs.open(os.environ['GITHUB_ENV'], 'a', 'utf-8') as file_handler:
               file_handler.write(env)
        shell: python

      - name: Set up Python for nox
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install nox
        run: |
            python -m pip install nox
            nox --version

      - name: Run tests
        run: nox -s test-${{ env.BASE }}

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        env:
          PYTHON: ${{ matrix.python }}
        with:
          flags: tests
          env_vars: PYTHON
          name: ${{ matrix.python }}
